version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretroot
      POSTGRES_DB: khipo-challenge
    
  khipo-api:
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://root:secretroot@postgres:5432/khipo-challenge?schema=eventoscia&connect_timeout=30&pool_timeout=30&socket_timeout=30
    container_name: khipo-api-back
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    depends_on:
      - db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s